### ISSUE TITLE
想请教一下大佬，bert-base-chinese里都有哪些文件呐，或者可以给指个路吗？

### ISSUE THREAD

**Issue by OohLeeGen** [illiterate/BertClassifier#3]

**Comment by illiterate** [comment]
可以下载HuggingFace上的这个：
https://huggingface.co/google-bert/bert-base-chinese

**Comment by OohLeeGen** [comment]
> 可以下载HuggingFace上的这个： https://huggingface.co/google-bert/bert-base-chinese

还有一个问题想要请教一下，epoch设置为10的话训练10轮花费大约多长时间呢，我租的4090D要跑一个半小时正常吗

**Comment by illiterate** [comment]
正常，如果每条数据的长度不长，可以把dataset.py中32行的max_length设置小一些，这样会更快

**Comment by illiterate** [comment]
正常，如果每条数据的长度不长，可以把dataset.py中32行的max_length设置小一些，这样会更快
