### ISSUE TITLE
linux环境运行出错

### ISSUE THREAD

**Issue by zhangqijjh** [illiterate/BertClassifier#4]
RuntimeError: CUDA error: unspecified launch failure
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by illiterate** [comment]
单机多卡，设置CUDA_VISIBLE_DEVICES就行了
```
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
```

**Comment by zhangqijjh** [comment]
修改后问题依旧：

(bert_text) XXi@SDRStation:~/BertClassifier$ python train.py
loading data from: /BertClassifier/data/cnews/cnews.train.txt
100%|████████████████████████████████████████████████████████| 50000/50000 [01:28<00:00, 565.19it/s]
loading data from: /BertClassifier/data/cnews/cnews.val.txt
100%|██████████████████████████████████████████████████████████| 5000/5000 [00:08<00:00, 583.13it/s]
/anaconda3/envs/bert_text/lib/python3.10/site-packages/transformers/optimization.py:588: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
Epoch 1 train:  10%|██▎                   | 1283/12500 [06:08<53:42,  3.48it/s, acc=0.5, loss=0.953]
Traceback (most recent call last):
  File "/BertClassifier/train.py", line 138, in <module>
    main()
  File "/BertClassifier/train.py", line 77, in main
    loss = criterion(output, label_id.to(device))
RuntimeError: CUDA error: unspecified launch failure
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by illiterate** [comment]
看日志是已经跑起来了，之后又报的错，说明代码没问题，估计你那边环境有问题，自己google一下吧

**Comment by zhangqijjh** [comment]
我怀疑可能还是环境配置问题，和代码无关。多谢大侠！
